Parameters:
  #VPC
  GitLabVPCCidrBlockParameter:
    Type: String
    Description: Customer's CIDR Block for the VPC
    Default: 10.0.0.0/16

  #PUBLIC SUBNET A
  GitLabPublicSubnetAAvailabilityZoneParameter:
    Type: AWS::EC2::AvailabilityZone::Name
    Description: Availability Zone for Public Subnet A
    Default: us-west-2a

  GitLabPublicSubnetACidrBlockParameter:
    Type: String
    Description: CIDR Block for Public Subnet A
    Default: 10.0.0.0/24

  #PUBLIC SUBNET B
  GitLabPublicSubnetBAvailabilityZoneParameter:
    Type: AWS::EC2::AvailabilityZone::Name
    Description: Availability Zone for Public Subnet B
    Default: us-west-2b

  GitLabPublicSubnetBCidrBlockParameter:
    Type: String
    Description: CIDR Block for Public Subnet B
    Default: 10.0.2.0/24

  #PRIVATE SUBNET A
  GitLabPrivateSubnetAAvailabilityZoneParameter:
    Type: AWS::EC2::AvailabilityZone::Name
    Description: Availability Zone for Private Subnet A
    Default: us-west-2a

  GitLabPrivateSubnetACidrBlockParameter:
    Type: String
    Description: CIDR Block for Private Subnet A
    Default: 10.0.1.0/24

  #PRIVATE SUBNET B
  GitLabPrivateSubnetBAvailabilityZoneParameter:
    Type: AWS::EC2::AvailabilityZone::Name
    Description: Availability Zone for Private Subnet B
    Default: us-west-2b

  GitLabPrivateSubnetBCidrBlockParameter:
    Type: String
    Description: CIDR Block for Private Subnet B
    Default: 10.0.3.0/24

  #SECURITY GROUPS
  GitLabLoadBalancerSecurityGroupCIDRParameter:
    Type: String
    Description: IPv4 address range for Load Balancer Security Group

  GitLabRDSSecurityGroupCIDRParameter:
    Type: String
    Description: CidrBlock for RDS Security Group
  
  #DATABASE
  GitLabDBInstanceClassParameter:
    Type: String
    Description: DB EC2 Instnace Class. Default is db.m4.large
    Default: db.m4.large  

  GitLabDBInstanceIdentifierParameter:
    Type: String
    Description: Name for the DB instance. 

  GitLabAllocatedStorageParameter:
    Type: String
    Description: Amount of storage in gigabytes to be allocated for the database intsance
    Default: '100' #minimum for PostgreSQL 

  #ELASTICACHE/REDIS
  GitLabCacheNodeTypeParameter:
    Type: String
    Description: Node type;  Multi-AZ not supported on T1 instances
    Default: cache.t3.medium 

  #GITLAB
  GitLabAvailabilityZoneParameter:
    Type: AWS::EC2::AvailabilityZone::Name
    Description: AZ for GitLab AMI 
  
  GitLabAMIParameter:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Description: Latest Gitlab AMI
    Default: /gitlab/gitlab/ami/gitlab-ce-12.2.5 

  GitLabInstanceTypeParameter:
    Type: String
    Description: EC2 instance type for GitLab AMI
    Default: c5.xlarge

  #GITALY
  GitLabGitalyAMIParameter: 
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Description: Latest Ubuntu AMI for Gitaly
    Default: /gitlab/gitaly/ami/ubuntu-server-18.04-lts-hvm

  GitLabGitalyInstanceTypeParameter:
    Type: String
    Description: EC2 instance type for Gitaly AMI
    Default: c5.xlarge

  #LAUNCH CONFIGURATIONS 
  GitLabLaunchConfogurationInstanceTypeParameter:
    Type: String 
    Description: EC2 instance type for launch configurations 
    Default: c5.xlarge
  
  GitLabLaunchConfigurationNameParameter:
    Type: String
    Description: Name of launch configuration 
    Default: gitlab-ha-launch-config
  
  #AUTO SCALING GROUP 
  GitLabHealthCheckGracePeriodParameter:
    Type: String
    Description: Number of seconds for health check grace period
    Default: '300'
  
  GitLabLoadBalancerHealthCheckTypeParameter:
    Type: String
    Description: The service to use for the health checks
    Default: ELB
    AllowedValues:
      - ELB
      - EC2
  
  GitLabMaxSizeParameter:
    Type: String
    Description: Max number of EC2 instances for auto scaling 
    Default: 4
  
  GitLabMinSizeParameter:
    Type: String
    Description: Min number of EC2 instances for auto scaling 
    Default: 2
  
  GitLabScalingPolicyTargetValueParameter:
    Type: String
    Description: Target for CPU use 
    Default: 60.0
  
  #AUTO SCALING  
  GitLabAutoScalingGroupDesiredCapacityParameter:
    Type: String 
    Description: Number of EC2 instances at start up 
    Default: '2'  
  
Resources:
  #S3 BUCKET
  GitlabS3Bucket:
    Type: AWS::S3::Bucket

  #ROLE W/ EMBEDDED POLICY
  GitLabS3Access:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - "sts:AssumeRole"
      Policies:
        - PolicyName: gl-s3-policy
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - "s3:AbortMultipleUpload"
                  - "s3:CompletemultipartUpload"
                  - "s3:ListBucket"
                  - "s3:PutObject"
                  - "s3:GetObject"
                  - "s3:DeleteObject"
                  - "s3:PutObjectAcl"
                Resource: !GetAtt GitlabS3Bucket.Arn

  GitLabS3InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref GitLabS3Access

  #VPC
  GitLabVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref GitLabVPCCidrBlockParameter
      EnableDnsHostnames: true

  #PUBLIC SUBNETS
  GitLabPublicSubnetA:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref GitLabVPC
      AvailabilityZone: !Ref GitLabPublicSubnetAAvailabilityZoneParameter
      CidrBlock: !Ref GitLabPublicSubnetACidrBlockParameter
      MapPublicIpOnLaunch: true

  GitLabPublicSubnetB:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref GitLabVPC
      AvailabilityZone: !Ref GitLabPublicSubnetBAvailabilityZoneParameter
      CidrBlock: !Ref GitLabPublicSubnetBCidrBlockParameter
      MapPublicIpOnLaunch: true

  #PRIVATE SUBNETS
  GitLabPrivateSubnetA:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref GitLabVPC
      AvailabilityZone: !Ref GitLabPrivateSubnetAAvailabilityZoneParameter
      CidrBlock: !Ref GitLabPrivateSubnetACidrBlockParameter
      MapPublicIpOnLaunch: false

  GitLabPrivateSubnetB:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref GitLabVPC
      AvailabilityZone: !Ref GitLabPrivateSubnetBAvailabilityZoneParameter
      CidrBlock: !Ref GitLabPrivateSubnetBCidrBlockParameter
      MapPublicIpOnLaunch: false

  #INTERNET GATEWAY
  GitLabInternetGateway:
    Type: AWS::EC2::InternetGateway

  GitLabGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref GitLabVPC
      InternetGatewayId: !Ref GitLabInternetGateway

  #EIP
  GitLabNATGatewayAElasticIP:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc

  GitLabNATGatewayBElasticIP:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc

  #NAT GATEWAY
  GitLabNATGatewayA:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: !GetAtt GitLabNATGatewayAElasticIP.AllocationId
      SubnetId: !Ref GitLabPublicSubnetA

  GitLabNatGatewayB:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: !GetAtt GitLabNATGatewayBElasticIP.AllocationId
      SubnetId: !Ref GitLabPublicSubnetB
  
  #NETWORK 
  GitLabPublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref GitLabVPC

  GitLabPublicRoute:
    Type: AWS::EC2::Route
    DependsOn: GitLabGatewayAttachment
    Properties:
      RouteTableId: !Ref GitLabPublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref GitLabInternetGateway

  GitLabPublicSubnetARouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref GitLabPublicSubnetA
      RouteTableId: !Ref GitLabPublicRouteTable

  GitLabPublicSubnetBRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref GitLabPublicSubnetB
      RouteTableId: !Ref GitLabPublicRouteTable

  GitLabPrivateRouteTableA:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref GitLabVPC

  GitLabPrivateRouteA:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref GitLabPrivateRouteTableA
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId: !Ref GitLabNATGatewayA

  GitLabPrivateSubnetARouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref GitLabPrivateSubnetA
      RouteTableId: !Ref GitLabPrivateRouteTableA

  GitLabPrivateRouteTableB:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref GitLabVPC

  GitLabPrivateRouteB:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref GitLabPrivateRouteTableB
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId: !Ref GitLabNatGatewayB

  GitLabPrivateSubnetBRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref GitLabPrivateSubnetB
      RouteTableId: !Ref GitLabPrivateRouteTableB

  #SECURITY GROUPS
  GitLabLoadBalancerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: gitlab-loadbalancer-sec-group
      GroupDescription: Allow HTTP and HTTPS traffic from anywhere
      VpcId: !Ref GitLabVPC
      SecurityGroupIngress:
        - IpProtocol: TCP
          FromPort: 80
          ToPort: 80
          CidrIp: !Ref GitLabLoadBalancerSecurityGroupCIDRParameter
        - IpProtocol: TCP
          FromPort: 443
          ToPort: 443
          CidrIp: !Ref GitLabLoadBalancerSecurityGroupCIDRParameter
        - IpProtocol: TCP
          FromPort: 22
          ToPort: 22
          CidrIp: !Ref GitLabLoadBalancerSecurityGroupCIDRParameter

  GitLabRDSSecurityGroup:
    Type: AWS::RDS::DBSecurityGroup
    Properties:
      DBSecurityGroupIngress:
        - CIDRIP: !Ref GitLabRDSSecurityGroupCIDRParameter
      GroupDescription: Security group for database that will allow inbound traffic from instances
      EC2VpcId: !Ref GitLabVPC
  
  GitLabRedisSecurityGroup:
    Type: AWS::EC2::SecurityGroup 
    Properties:
      GroupName: gitlab-redis-sec-group
      SecurityGroupIngress:
        -  IpProtocol: TCP
           FromPort: 6379
           ToPort: 6379
           SourceSecurityGroupId: !Ref GitLabLoadBalancerSecurityGroup 
      GroupDescription: Security group for Redis 
      VpcId: !Ref GitLabVPC

  GitLabGitalySecurityGroup: 
    Type: AWS::EC2::SecurityGroup 
    Properties:
      GroupName: gitlab-gitaly-sec-group 
      SecurityGroupIngress:
        - IpProtocol: TCP
          FromPort: 22
          ToPort: 22
        - IpProtocol: TCP
          FromPort: 8075
          ToPort: 8075
          SourceSecurityGroupId: !Ref GitLabLoadBalancerSecurityGroup
      GroupDescription: Security Group for Gitaly
      VpcId: !Ref GitLabVPC

  #LOAD BALANCER
  GitLabLoadBalancer:
    Type: AWS::ElasticLoadBalancing::LoadBalancer
    Properties:
      Listeners:
        - LoadBalancerPort: "80"
          InstancePort: "80"
          Protocol: HTTP
        #- LoadBalancerPort: "443"
        #  InstancePort: "443"
        #  Protocol: HTTPS
        - LoadBalancerPort: "22"
          InstancePort: "22"
          Protocol: TCP
      HealthCheck: #set at default
        Target: HTTP:80/index.html #HTTP is console default, TCP is CLI default
        Timeout: "5"
        Interval: "30"
        UnhealthyThreshold: "2"
        HealthyThreshold: "10"
      LoadBalancerName: GitLabLoadBalancer
      Scheme: internet-facing
      SecurityGroups:
        - !Ref GitLabLoadBalancerSecurityGroup
      Instances: 
        - !Ref GitLab
      Subnets:
        - !Ref GitLabPublicSubnetA
        - !Ref GitLabPublicSubnetB

  #RDS POSTGRESQL DATABASE
  GitLabDBSubnetGroup: 
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Group includes GitLabPrivateSubnetA and GitLabPrivateSubnetB
      SubnetIds:
        - !Ref GitLabPrivateSubnetA
        - !Ref GitLabPrivateSubnetB 

  GitLabDBSecrets: 
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: DB password for the master user.
      GenerateSecretString: 
        SecretStringTemplate: '{"username": "testuser"}'
        GenerateStringKey: 'password'
        PasswordLength: 16
        ExcludeCharacters: '"@/\'

  GitLabDB:
    Type: AWS::RDS::DBInstance 
    Properties: 
      AllocatedStorage: !Ref GitLabAllocatedStorageParameter 
      AutoMinorVersionUpgrade: False
      BackupRetentionPeriod: 35 
      DBInstanceClass: !Ref GitLabDBInstanceClassParameter 
      DBInstanceIdentifier: !Ref GitLabDBInstanceIdentifierParameter
      DBSecurityGroups: 
        - !Ref GitLabRDSSecurityGroup
      DBSubnetGroupName: !Ref GitLabDBSubnetGroup 
      Engine: postgres
      EngineVersion: '12.3' #newest 
      MasterUsername: !Join ['', ['{{resolve:secretsmanager:', !Ref GitLabDBSecrets, ':SecretString:username}}' ]]
      MasterUserPassword: !Join ['', ['{{resolve:secretsmanager:', !Ref GitLabDBSecrets, ':SecretString:password}}' ]] 
      MultiAZ: True

  GitLabSecretTargetAttachment:
    Type: AWS::SecretsManager::SecretTargetAttachment
    Properties: 
      SecretId: !Ref GitLabDBSecrets
      TargetId: !Ref GitLabDB
      TargetType: AWS::RDS::DBInstance 

  #REDIS WITH ELASTICACHE
  GitLabRedisSubnetGroup: 
    Type: AWS::ElastiCache::SubnetGroup 
    Properties:
      CacheSubnetGroupName: gitlab-redis-group
      Description: Group includes GitLabPrivateSubnetA and GitLabPrivateSubnetB
      SubnetIds:
        - !Ref GitLabPrivateSubnetA
        - !Ref GitLabPrivateSubnetB 
  
  GitLabElastiCacheCluster: 
    Type: AWS::ElastiCache::CacheCluster 
    Properties: 
      NumCacheNodes: 1
      ClusterName: gitlab-redis
      Engine: redis
      EngineVersion: '5.0.6' #newest
      Port: 6379 
      CacheNodeType: !Ref GitLabCacheNodeTypeParameter
      CacheSubnetGroupName: !Ref GitLabRedisSubnetGroup
      PreferredAvailabilityZones: 
        - !GetAtt GitLabPrivateSubnetA.AvailabilityZone 
      AZMode: single-az
      VpcSecurityGroupIds: 
        - !GetAtt GitLabRedisSecurityGroup.GroupId

  #GITLAB
  GitLab:
    Type: AWS::EC2::Instance
    Properties: 
      AvailabilityZone: !Ref GitLabAvailabilityZoneParameter
      ImageId: !Ref GitLabAMIParameter 
      InstanceType: !Ref GitLabInstanceTypeParameter 
      SubnetId: !Ref GitLabPrivateSubnetA 
      SecurityGroupIds: 
        - !Ref GitLabLoadBalancerSecurityGroup
      Tags: 
        - Key: Name
          Value: GitLab
 
  #GITALY
  Gitaly:
    Type: AWS::EC2::Instance
    Properties: 
      AvailabilityZone: !Ref GitLabAvailabilityZoneParameter
      ImageId: !Ref GitLabGitalyAMIParameter
      InstanceType: !Ref GitLabGitalyInstanceTypeParameter
      SubnetId: !Ref GitLabPrivateSubnetA 
      SecurityGroupIds: 
        - !Ref GitLabGitalySecurityGroup
      Tags: 
        - Key: Name
          Value: Gitaly

  #LAUNCH CONFIGURATIONS
  GitLabLaunchConfigurations:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties: 
      ImageId: !Ref GitLabAMIParameter
      InstanceType: !Ref GitLabLaunchConfogurationInstanceTypeParameter
      LaunchConfigurationName: !Ref GitLabLaunchConfigurationNameParameter
      IamInstanceProfile: !Ref GitLabS3InstanceProfile
      SecurityGroups:
        - !Ref GitLabLoadBalancerSecurityGroup
  
  #AUTO SCALING GROUP 
  GitLabAutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AutoScalingGroupName: gitlab-auto-scaling-group
      LaunchConfigurationName: !Ref GitLabLaunchConfigurations 
      DesiredCapacity: !Ref GitLabAutoScalingGroupDesiredCapacityParameter
      VPCZoneIdentifier: 
        - !Ref GitLabPrivateSubnetA
        - !Ref GitLabPrivateSubnetB
      LoadBalancerNames:
        - !Ref GitLabLoadBalancer
      HealthCheckType: !Ref GitLabLoadBalancerHealthCheckTypeParameter 
      HealthCheckGracePeriod: !Ref GitLabHealthCheckGracePeriodParameter 
      MaxSize: !Ref GitLabMaxSizeParameter
      MinSize: !Ref GitLabMinSizeParameter

  GitLabAutoScalingScalingPolicy: 
    Type: AWS::AutoScaling::ScalingPolicy
    Properties:
      AdjustmentType: ChangeInCapacity
      PolicyType: TargetTrackingScaling
      TargetTrackingConfiguration:
        PredefinedMetricSpecification:
          PredefinedMetricType: ASGAverageCPUUtilization
        TargetValue: !Ref GitLabScalingPolicyTargetValueParameter
      AutoScalingGroupName: !Ref GitLabAutoScalingGroup
      EstimatedInstanceWarmup: 120 


